
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "Destructor.py", line 88, in <module>
    game.update_frame()
  File "C:\Users\creat\Desktop\cs\CIS365\halite\hlt\networ
